# Introduction to Remote Sensing

## Summary

This week, we looked at the fundamentals of remote sensing focusing on its technical workings, and applications. The focus was on understanding how electromagnetic energy is used to gather data about the Earth's surface. The lectures introduced key concepts, including the electromagnetic spectrum, sensor types, and image processing techniques.

Remote sensing is the science of obtaining information about the Earth’s via sensors. This information is obtained by sensors that observe energy, usually from the sun, reflected or emitted from the earth’s surface [@tempfli2009]. This energy can be modelled as waves, where the shorter the wavelength, the higher the frequency and energy. These sensors measure how different materials reflect or absorb energy at specific wavelengths. Remote sensing operates across bands on the electromagnetic spectrum, including wavelengths visible to the human eye and beyond, like near-infrared radiation. For example, healthy vegetation reflects a lot of near-infrared energy because of its cellular structure, while unhealthy vegetation reflects less [@butcher2016]. By analysing these spectral reflectance curves, scientists can identify spectral signatures for plant health, soil types, or water quality using specialised software such as SNAP and R (which we used in our practical).

Sensors can be passive, relying on naturally reflected sunlight, or active, emitting their own energy (e.g., radar). This capability allows scientists to gather data on vegetation health, land use, and atmospheric conditions [@tempfli2009].

Reflecting on this introductory week, the power of remote sensing is apparent. Its ability to provide a continuous view of the planet opens up possibilities for environmental monitoring, resource management, and disaster response.

## Application

In the practical we looked at data from Landsat 8 and Sentinel-2; two of the most widely used Earth observation missions that provide freely available satellite data. The ready availability of data from these missions has fundamentally changed the landscape of remote sensing research, leading to a huge increase in applications across different fields

Landsat 8, launched in 2013, offers a spatial resolution of 30 meters and 16-day revisit intervals [@landsat]. It captures imagery across nine spectral bands using its sensor (Operational Land Imager). It differs from Sentinel-2 as it captures thermal data at a resolution of 100 meters.

Therefore, it has become a key data source for studies requiring long-term trend analysis and surface temperature information. For instance, [@kaplan2018] utilised Landsat's thermal bands to map urban heat islands in Skopje, tracking their expansion over multiple years. Another example is [@fahnestock2016], with their work on mapping glacier melting rates.

Sentinel-2, launched in 2015 and 2024 as a dual-satellite mission, provides a more frequent revisit time of five days and captures data across 13 spectral bands at spatial resolutions ranging from 10 to 60 meters [@esa]. The relatively short revisit period makes it ideal for near real-time monitoring of dynamic events such as natural disasters.

[@jelének2021], for example, showcased the effectiveness of Sentinel data in automatically detecting damage from earthquakes, providing crucial information for disaster response efforts. As well as the technical aspects of Sentinel data, they highlight its accessibility as a big asset for timely impact assessments [@jelének2021].

Chaves et al., (2020) also notes how the red-edge bands are particularly good for assessing vegetation health, which enable researchers to detect subtle changes in plant conditions, making it useful for environmental research [@chaves2020].

Both Landsat 8 and Sentinel-2 are great for monitoring Earth's surface, but as mentioned in the paragraphs above, their sensors capture data slightly differently [@mandanici2016]. This means you need to be careful when combining data from the two sensors, taking into consideration the differences in bands and resolution.

Overall, it is clear that this is an exciting time for remote sensing research - From a European Space Agency report, released at the beginning of 2025 research using ESA earth observation satellites has exploded since 2002 [@esscesa2025]. "According to statistics provided by ESA, over 4,000 scientific publications utilising ESA and Sentinel satellites have been published in peer-reviewed journals in 2024 alone" [@esscesa2025, pp.42]

![European Space Agency [@esscesa2025]](publications.png)

Whilst Landsat and Sentinel satellites dominant research due to their availability, there are also plenty of private commercial earth observation missions being launched by commercial companies as shown below.

![EO satellite companies [@aravind2025]](eosatellitecompanies.png)

## Reflection

I am impressed by how much remote sensing data is freely available despite the million of pounds cost of launching satellites and all the research involved. They appear to have democratised remote sensing research, allowing for policy development and R&D in many domains including agriculture and urban planning. It lowers the barrier to entry for researchers globally, allowing for a wide range of institutions and individuals to contribute to the understanding of Earth.

I also found a very helpful newsletter by TerraWatch Space called [Last Week in Observation](https://newsletter.terrawatchspace.com/) that releases weekly updates on the commercial and academic world in remote sensing, so I will keep an eye on that for any new research or innovations in the field.

Looking ahead, the challenge lies in effectively translating remote sensing data into actionable policies. This week has sparked an interest in exploring how these tools and data can be applied to ongoing environmental issues. I expect these skills and this knowledge, or at least something similar, will be highly relevant and valuable in the future.
