project:
  type: book
  output-dir: docs

book:
  title: "Remotely Sensing Learning Diary"
  author: "Chris Richman"
  date: "01/21/2025"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_portfolio.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

